name: Render Latext Text
on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed .tex files
        id: diff
        run: |
            echo "::set-output name=TEX_FILES::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '.tex')"
      - name: Tex file render
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ steps.diff.outputs.TEX_FILES }}
