name: Render Latext Text
on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get .tex files
        id: diff
        run: |
            echo "::set-output name=TEX_FILES::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '.tex')"
      - name: Tex file render
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ steps.diff.outputs.TEX_FILES }}
      - name: Get .pdf files
        id: pdfFiles
        run: |
              echo "::set-output name=PDF_FILES::$(ls | grep '.pdf')"
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: ${{ steps.pdfFiles.outputs.PDF_FILES }}