name: Render Latext Text
on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name:    
        uses: xu-cheng/latex-action@v3
        with:
          root_file: git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep ".py"
