name: Render Latext Text
on: push



jobs:
  Test:
    runs-on: ubuntu-latest
    env: 
      TEX_FILES: value
      PDF_FILES: value
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get .tex files
        id: diff
        run: |
            echo "{TEX_FILES}={git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '.tex'}" >> $TEX_FILES
      - name: Tex file render
        run: echo $TEX_FILES
        # uses: xu-cheng/latex-action@v3
        # with:
        #   root_file: ${{github.env.TEX_FILES}}
      # - name: Get .pdf files
      #   id: pdfFiles
      #   run: |
      #         echo "{PDF_FILES}={ls | grep '.pdf'}" >> PDF_FILES
      # - uses: actions/download-artifact@v4
      #   with:
      #       name: .pdf
      #       path: /home/valentinere/Documents/test       
      # - name: Upload PDF file
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: PDF
      #     path: ${{ github.env.PDF_FILES }}