name: Render Latext Text
on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get .tex files
        run: |
          echo "TEX_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '.tex')" >> $GITHUB_ENV
      - name: Tex file render
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ env.TEX_FILES }}
      - name: Set up Python and dep
        uses: actions/setup-python@v5
      - run: pip install PyDrive2 
      - name: Script 
        run: python sender.py